export const city_sample = [
  { site_id: "新北市板橋區", city: "新北市", district: "板橋區" },
  { site_id: "新北市三重區", city: "新北市", district: "三重區" },
  { site_id: "新北市中和區", city: "新北市", district: "中和區" },
  { site_id: "新北市永和區", city: "新北市", district: "永和區" },
  { site_id: "新北市新莊區", city: "新北市", district: "新莊區" },
  { site_id: "新北市新店區", city: "新北市", district: "新店區" },
  { site_id: "新北市樹林區", city: "新北市", district: "樹林區" },
  { site_id: "新北市鶯歌區", city: "新北市", district: "鶯歌區" },
  { site_id: "新北市三峽區", city: "新北市", district: "三峽區" },
  { site_id: "新北市淡水區", city: "新北市", district: "淡水區" },
  { site_id: "新北市汐止區", city: "新北市", district: "汐止區" },
  { site_id: "新北市瑞芳區", city: "新北市", district: "瑞芳區" },
  { site_id: "新北市土城區", city: "新北市", district: "土城區" },
  { site_id: "新北市蘆洲區", city: "新北市", district: "蘆洲區" },
  { site_id: "新北市五股區", city: "新北市", district: "五股區" },
  { site_id: "新北市泰山區", city: "新北市", district: "泰山區" },
  { site_id: "新北市林口區", city: "新北市", district: "林口區" },
  { site_id: "新北市深坑區", city: "新北市", district: "深坑區" },
  { site_id: "新北市石碇區", city: "新北市", district: "石碇區" },
  { site_id: "新北市坪林區", city: "新北市", district: "坪林區" },
  { site_id: "新北市三芝區", city: "新北市", district: "三芝區" },
  { site_id: "新北市石門區", city: "新北市", district: "石門區" },
  { site_id: "新北市八里區", city: "新北市", district: "八里區" },
  { site_id: "新北市平溪區", city: "新北市", district: "平溪區" },
  { site_id: "新北市雙溪區", city: "新北市", district: "雙溪區" },
  { site_id: "新北市貢寮區", city: "新北市", district: "貢寮區" },
  { site_id: "新北市金山區", city: "新北市", district: "金山區" },
  { site_id: "新北市萬里區", city: "新北市", district: "萬里區" },
  { site_id: "新北市烏來區", city: "新北市", district: "烏來區" },
  { site_id: "臺北市松山區", city: "臺北市", district: "松山區" },
  { site_id: "臺北市信義區", city: "臺北市", district: "信義區" },
  { site_id: "臺北市大安區", city: "臺北市", district: "大安區" },
  { site_id: "臺北市中山區", city: "臺北市", district: "中山區" },
  { site_id: "臺北市中正區", city: "臺北市", district: "中正區" },
  { site_id: "臺北市大同區", city: "臺北市", district: "大同區" },
  { site_id: "臺北市萬華區", city: "臺北市", district: "萬華區" },
  { site_id: "臺北市文山區", city: "臺北市", district: "文山區" },
  { site_id: "臺北市南港區", city: "臺北市", district: "南港區" },
  { site_id: "臺北市內湖區", city: "臺北市", district: "內湖區" },
  { site_id: "臺北市士林區", city: "臺北市", district: "士林區" },
  { site_id: "臺北市北投區", city: "臺北市", district: "北投區" },
  { site_id: "桃園市桃園區", city: "桃園市", district: "桃園區" },
  { site_id: "桃園市中壢區", city: "桃園市", district: "中壢區" },
  { site_id: "桃園市大溪區", city: "桃園市", district: "大溪區" },
  { site_id: "桃園市楊梅區", city: "桃園市", district: "楊梅區" },
  { site_id: "桃園市蘆竹區", city: "桃園市", district: "蘆竹區" },
  { site_id: "桃園市大園區", city: "桃園市", district: "大園區" },
  { site_id: "桃園市龜山區", city: "桃園市", district: "龜山區" },
  { site_id: "桃園市八德區", city: "桃園市", district: "八德區" },
  { site_id: "桃園市龍潭區", city: "桃園市", district: "龍潭區" },
  { site_id: "桃園市平鎮區", city: "桃園市", district: "平鎮區" },
  { site_id: "桃園市新屋區", city: "桃園市", district: "新屋區" },
  { site_id: "桃園市觀音區", city: "桃園市", district: "觀音區" },
  { site_id: "桃園市復興區", city: "桃園市", district: "復興區" },
  { site_id: "臺中市中區", city: "臺中市", district: "中區" },
  { site_id: "臺中市東區", city: "臺中市", district: "東區" },
  { site_id: "臺中市南區", city: "臺中市", district: "南區" },
  { site_id: "臺中市西區", city: "臺中市", district: "西區" },
  { site_id: "臺中市北區", city: "臺中市", district: "北區" },
  { site_id: "臺中市西屯區", city: "臺中市", district: "西屯區" },
  { site_id: "臺中市南屯區", city: "臺中市", district: "南屯區" },
  { site_id: "臺中市北屯區", city: "臺中市", district: "北屯區" },
  { site_id: "臺中市豐原區", city: "臺中市", district: "豐原區" },
  { site_id: "臺中市東勢區", city: "臺中市", district: "東勢區" },
  { site_id: "臺中市大甲區", city: "臺中市", district: "大甲區" },
  { site_id: "臺中市清水區", city: "臺中市", district: "清水區" },
  { site_id: "臺中市沙鹿區", city: "臺中市", district: "沙鹿區" },
  { site_id: "臺中市梧棲區", city: "臺中市", district: "梧棲區" },
  { site_id: "臺中市后里區", city: "臺中市", district: "后里區" },
  { site_id: "臺中市神岡區", city: "臺中市", district: "神岡區" },
  { site_id: "臺中市潭子區", city: "臺中市", district: "潭子區" },
  { site_id: "臺中市大雅區", city: "臺中市", district: "大雅區" },
  { site_id: "臺中市新社區", city: "臺中市", district: "新社區" },
  { site_id: "臺中市石岡區", city: "臺中市", district: "石岡區" },
  { site_id: "臺中市外埔區", city: "臺中市", district: "外埔區" },
  { site_id: "臺中市大安區", city: "臺中市", district: "大安區" },
  { site_id: "臺中市烏日區", city: "臺中市", district: "烏日區" },
  { site_id: "臺中市大肚區", city: "臺中市", district: "大肚區" },
  { site_id: "臺中市龍井區", city: "臺中市", district: "龍井區" },
  { site_id: "臺中市霧峰區", city: "臺中市", district: "霧峰區" },
  { site_id: "臺中市太平區", city: "臺中市", district: "太平區" },
  { site_id: "臺中市大里區", city: "臺中市", district: "大里區" },
  { site_id: "臺中市和平區", city: "臺中市", district: "和平區" },
  { site_id: "臺南市新營區", city: "臺南市", district: "新營區" },
  { site_id: "臺南市鹽水區", city: "臺南市", district: "鹽水區" },
  { site_id: "臺南市白河區", city: "臺南市", district: "白河區" },
  { site_id: "臺南市柳營區", city: "臺南市", district: "柳營區" },
  { site_id: "臺南市後壁區", city: "臺南市", district: "後壁區" },
  { site_id: "臺南市東山區", city: "臺南市", district: "東山區" },
  { site_id: "臺南市麻豆區", city: "臺南市", district: "麻豆區" },
  { site_id: "臺南市下營區", city: "臺南市", district: "下營區" },
  { site_id: "臺南市六甲區", city: "臺南市", district: "六甲區" },
  { site_id: "臺南市官田區", city: "臺南市", district: "官田區" },
  { site_id: "臺南市大內區", city: "臺南市", district: "大內區" },
  { site_id: "臺南市佳里區", city: "臺南市", district: "佳里區" },
  { site_id: "臺南市學甲區", city: "臺南市", district: "學甲區" },
  { site_id: "臺南市西港區", city: "臺南市", district: "西港區" },
  { site_id: "臺南市七股區", city: "臺南市", district: "七股區" },
  { site_id: "臺南市將軍區", city: "臺南市", district: "將軍區" },
  { site_id: "臺南市北門區", city: "臺南市", district: "北門區" },
  { site_id: "臺南市新化區", city: "臺南市", district: "新化區" },
  { site_id: "臺南市善化區", city: "臺南市", district: "善化區" },
  { site_id: "臺南市新市區", city: "臺南市", district: "新市區" },
  { site_id: "臺南市安定區", city: "臺南市", district: "安定區" },
  { site_id: "臺南市山上區", city: "臺南市", district: "山上區" },
  { site_id: "臺南市玉井區", city: "臺南市", district: "玉井區" },
  { site_id: "臺南市楠西區", city: "臺南市", district: "楠西區" },
  { site_id: "臺南市南化區", city: "臺南市", district: "南化區" },
  { site_id: "臺南市左鎮區", city: "臺南市", district: "左鎮區" },
  { site_id: "臺南市仁德區", city: "臺南市", district: "仁德區" },
  { site_id: "臺南市歸仁區", city: "臺南市", district: "歸仁區" },
  { site_id: "臺南市關廟區", city: "臺南市", district: "關廟區" },
  { site_id: "臺南市龍崎區", city: "臺南市", district: "龍崎區" },
  { site_id: "臺南市永康區", city: "臺南市", district: "永康區" },
  { site_id: "臺南市東區", city: "臺南市", district: "東區" },
  { site_id: "臺南市南區", city: "臺南市", district: "南區" },
  { site_id: "臺南市北區", city: "臺南市", district: "北區" },
  { site_id: "臺南市中西區", city: "臺南市", district: "中西區" },
  { site_id: "高雄市鹽埕區", city: "高雄市", district: "鹽埕區" },
  { site_id: "高雄市鼓山區", city: "高雄市", district: "鼓山區" },
  { site_id: "高雄市左營區", city: "高雄市", district: "左營區" },
  { site_id: "高雄市楠梓區", city: "高雄市", district: "楠梓區" },
  { site_id: "高雄市三民區", city: "高雄市", district: "三民區" },
  { site_id: "高雄市新興區", city: "高雄市", district: "新興區" },
  { site_id: "高雄市前金區", city: "高雄市", district: "前金區" },
  { site_id: "高雄市苓雅區", city: "高雄市", district: "苓雅區" },
  { site_id: "高雄市前鎮區", city: "高雄市", district: "前鎮區" },
  { site_id: "高雄市旗津區", city: "高雄市", district: "旗津區" },
  { site_id: "高雄市小港區", city: "高雄市", district: "小港區" },
  { site_id: "高雄市鳳山區", city: "高雄市", district: "鳳山區" },
  { site_id: "高雄市林園區", city: "高雄市", district: "林園區" },
  { site_id: "高雄市大寮區", city: "高雄市", district: "大寮區" },
  { site_id: "高雄市大樹區", city: "高雄市", district: "大樹區" },
  { site_id: "高雄市大社區", city: "高雄市", district: "大社區" },
  { site_id: "高雄市仁武區", city: "高雄市", district: "仁武區" },
  { site_id: "高雄市鳥松區", city: "高雄市", district: "鳥松區" },
  { site_id: "高雄市岡山區", city: "高雄市", district: "岡山區" },
  { site_id: "高雄市橋頭區", city: "高雄市", district: "橋頭區" },
  { site_id: "高雄市燕巢區", city: "高雄市", district: "燕巢區" },
  { site_id: "高雄市田寮區", city: "高雄市", district: "田寮區" },
  { site_id: "高雄市阿蓮區", city: "高雄市", district: "阿蓮區" },
  { site_id: "高雄市路竹區", city: "高雄市", district: "路竹區" },
  { site_id: "高雄市湖內區", city: "高雄市", district: "湖內區" },
  { site_id: "高雄市茄萣區", city: "高雄市", district: "茄萣區" },
  { site_id: "高雄市永安區", city: "高雄市", district: "永安區" },
  { site_id: "高雄市彌陀區", city: "高雄市", district: "彌陀區" },
  { site_id: "高雄市梓官區", city: "高雄市", district: "梓官區" },
  { site_id: "高雄市旗山區", city: "高雄市", district: "旗山區" },
  { site_id: "高雄市美濃區", city: "高雄市", district: "美濃區" },
  { site_id: "高雄市六龜區", city: "高雄市", district: "六龜區" },
  { site_id: "高雄市甲仙區", city: "高雄市", district: "甲仙區" },
  { site_id: "高雄市杉林區", city: "高雄市", district: "杉林區" },
  { site_id: "高雄市內門區", city: "高雄市", district: "內門區" },
  { site_id: "高雄市茂林區", city: "高雄市", district: "茂林區" },
  { site_id: "高雄市桃源區", city: "高雄市", district: "桃源區" },
  { site_id: "高雄市那瑪夏區", city: "高雄市", district: "那瑪夏區" },
  { site_id: "基隆市仁愛區", city: "基隆市", district: "仁愛區" },
  { site_id: "基隆市信義區", city: "基隆市", district: "信義區" },
  { site_id: "基隆市中正區", city: "基隆市", district: "中正區" },
  { site_id: "基隆市中山區", city: "基隆市", district: "中山區" },
  { site_id: "基隆市安樂區", city: "基隆市", district: "安樂區" },
  { site_id: "基隆市暖暖區", city: "基隆市", district: "暖暖區" },
  { site_id: "基隆市七堵區", city: "基隆市", district: "七堵區" },
  { site_id: "新竹市東區", city: "新竹市", district: "東區" },
  { site_id: "新竹市北區", city: "新竹市", district: "北區" },
  { site_id: "新竹市香山區", city: "新竹市", district: "香山區" },
  { site_id: "嘉義市東區", city: "嘉義市", district: "東區" },
  { site_id: "嘉義市西區", city: "嘉義市", district: "西區" },
  { site_id: "新竹縣竹北市", city: "新竹縣", district: "竹北市" },
  { site_id: "新竹縣湖口鄉", city: "新竹縣", district: "湖口鄉" },
  { site_id: "新竹縣新豐鄉", city: "新竹縣", district: "新豐鄉" },
  { site_id: "新竹縣新埔鎮", city: "新竹縣", district: "新埔鎮" },
  { site_id: "新竹縣關西鎮", city: "新竹縣", district: "關西鎮" },
  { site_id: "新竹縣芎林鄉", city: "新竹縣", district: "芎林鄉" },
  { site_id: "新竹縣寶山鄉", city: "新竹縣", district: "寶山鄉" },
  { site_id: "新竹縣竹東鎮", city: "新竹縣", district: "竹東鎮" },
  { site_id: "新竹縣五峰鄉", city: "新竹縣", district: "五峰鄉" },
  { site_id: "新竹縣橫山鄉", city: "新竹縣", district: "橫山鄉" },
  { site_id: "新竹縣尖石鄉", city: "新竹縣", district: "尖石鄉" },
  { site_id: "新竹縣北埔鄉", city: "新竹縣", district: "北埔鄉" },
  { site_id: "新竹縣峨眉鄉", city: "新竹縣", district: "峨眉鄉" },
  { site_id: "苗栗縣竹南鎮", city: "苗栗縣", district: "竹南鎮" },
  { site_id: "苗栗縣頭份市", city: "苗栗縣", district: "頭份市" },
  { site_id: "苗栗縣三灣鄉", city: "苗栗縣", district: "三灣鄉" },
  { site_id: "苗栗縣南庄鄉", city: "苗栗縣", district: "南庄鄉" },
  { site_id: "苗栗縣獅潭鄉", city: "苗栗縣", district: "獅潭鄉" },
  { site_id: "苗栗縣後龍鎮", city: "苗栗縣", district: "後龍鎮" },
  { site_id: "苗栗縣通霄鎮", city: "苗栗縣", district: "通霄鎮" },
  { site_id: "苗栗縣苑裡鎮", city: "苗栗縣", district: "苑裡鎮" },
  { site_id: "苗栗縣苗栗市", city: "苗栗縣", district: "苗栗市" },
  { site_id: "苗栗縣造橋鄉", city: "苗栗縣", district: "造橋鄉" },
  { site_id: "苗栗縣頭屋鄉", city: "苗栗縣", district: "頭屋鄉" },
  { site_id: "苗栗縣公館鄉", city: "苗栗縣", district: "公館鄉" },
  { site_id: "苗栗縣大湖鄉", city: "苗栗縣", district: "大湖鄉" },
  { site_id: "苗栗縣泰安鄉", city: "苗栗縣", district: "泰安鄉" },
  { site_id: "苗栗縣銅鑼鄉", city: "苗栗縣", district: "銅鑼鄉" },
  { site_id: "苗栗縣三義鄉", city: "苗栗縣", district: "三義鄉" },
  { site_id: "苗栗縣西湖鄉", city: "苗栗縣", district: "西湖鄉" },
  { site_id: "苗栗縣卓蘭鎮", city: "苗栗縣", district: "卓蘭鎮" },
  { site_id: "彰化縣彰化市", city: "彰化縣", district: "彰化市" },
  { site_id: "彰化縣芬園鄉", city: "彰化縣", district: "芬園鄉" },
  { site_id: "彰化縣花壇鄉", city: "彰化縣", district: "花壇鄉" },
  { site_id: "彰化縣秀水鄉", city: "彰化縣", district: "秀水鄉" },
  { site_id: "彰化縣鹿港鎮", city: "彰化縣", district: "鹿港鎮" },
  { site_id: "彰化縣福興鄉", city: "彰化縣", district: "福興鄉" },
  { site_id: "彰化縣線西鄉", city: "彰化縣", district: "線西鄉" },
  { site_id: "彰化縣和美鎮", city: "彰化縣", district: "和美鎮" },
  { site_id: "彰化縣伸港鄉", city: "彰化縣", district: "伸港鄉" },
  { site_id: "彰化縣員林市", city: "彰化縣", district: "員林市" },
  { site_id: "彰化縣社頭鄉", city: "彰化縣", district: "社頭鄉" },
  { site_id: "彰化縣永靖鄉", city: "彰化縣", district: "永靖鄉" },
  { site_id: "彰化縣埔心鄉", city: "彰化縣", district: "埔心鄉" },
  { site_id: "彰化縣溪湖鎮", city: "彰化縣", district: "溪湖鎮" },
  { site_id: "彰化縣大村鄉", city: "彰化縣", district: "大村鄉" },
  { site_id: "彰化縣埔鹽鄉", city: "彰化縣", district: "埔鹽鄉" },
  { site_id: "彰化縣田中鎮", city: "彰化縣", district: "田中鎮" },
  { site_id: "彰化縣北斗鎮", city: "彰化縣", district: "北斗鎮" },
  { site_id: "彰化縣田尾鄉", city: "彰化縣", district: "田尾鄉" },
  { site_id: "彰化縣埤頭鄉", city: "彰化縣", district: "埤頭鄉" },
  { site_id: "彰化縣溪州鄉", city: "彰化縣", district: "溪州鄉" },
  { site_id: "彰化縣竹塘鄉", city: "彰化縣", district: "竹塘鄉" },
  { site_id: "彰化縣二林鎮", city: "彰化縣", district: "二林鎮" },
  { site_id: "彰化縣大城鄉", city: "彰化縣", district: "大城鄉" },
  { site_id: "彰化縣芳苑鄉", city: "彰化縣", district: "芳苑鄉" },
  { site_id: "彰化縣二水鄉", city: "彰化縣", district: "二水鄉" },
  { site_id: "南投縣南投市", city: "南投縣", district: "南投市" },
  { site_id: "南投縣中寮鄉", city: "南投縣", district: "中寮鄉" },
  { site_id: "南投縣草屯鎮", city: "南投縣", district: "草屯鎮" },
  { site_id: "南投縣國姓鄉", city: "南投縣", district: "國姓鄉" },
  { site_id: "南投縣埔里鎮", city: "南投縣", district: "埔里鎮" },
  { site_id: "南投縣仁愛鄉", city: "南投縣", district: "仁愛鄉" },
  { site_id: "南投縣名間鄉", city: "南投縣", district: "名間鄉" },
  { site_id: "南投縣集集鎮", city: "南投縣", district: "集集鎮" },
  { site_id: "南投縣水里鄉", city: "南投縣", district: "水里鄉" },
  { site_id: "南投縣魚池鄉", city: "南投縣", district: "魚池鄉" },
  { site_id: "南投縣信義鄉", city: "南投縣", district: "信義鄉" },
  { site_id: "南投縣竹山鎮", city: "南投縣", district: "竹山鎮" },
  { site_id: "南投縣鹿谷鄉", city: "南投縣", district: "鹿谷鄉" },
  { site_id: "雲林縣斗南鎮", city: "雲林縣", district: "斗南鎮" },
  { site_id: "雲林縣大埤鄉", city: "雲林縣", district: "大埤鄉" },
  { site_id: "雲林縣虎尾鎮", city: "雲林縣", district: "虎尾鎮" },
  { site_id: "雲林縣土庫鎮", city: "雲林縣", district: "土庫鎮" },
  { site_id: "雲林縣褒忠鄉", city: "雲林縣", district: "褒忠鄉" },
  { site_id: "雲林縣東勢鄉", city: "雲林縣", district: "東勢鄉" },
  { site_id: "雲林縣臺西鄉", city: "雲林縣", district: "臺西鄉" },
  { site_id: "雲林縣崙背鄉", city: "雲林縣", district: "崙背鄉" },
  { site_id: "雲林縣麥寮鄉", city: "雲林縣", district: "麥寮鄉" },
  { site_id: "雲林縣斗六市", city: "雲林縣", district: "斗六市" },
  { site_id: "雲林縣林內鄉", city: "雲林縣", district: "林內鄉" },
  { site_id: "雲林縣古坑鄉", city: "雲林縣", district: "古坑鄉" },
  { site_id: "雲林縣莿桐鄉", city: "雲林縣", district: "莿桐鄉" },
  { site_id: "雲林縣西螺鎮", city: "雲林縣", district: "西螺鎮" },
  { site_id: "雲林縣二崙鄉", city: "雲林縣", district: "二崙鄉" },
  { site_id: "雲林縣北港鎮", city: "雲林縣", district: "北港鎮" },
  { site_id: "雲林縣水林鄉", city: "雲林縣", district: "水林鄉" },
  { site_id: "雲林縣口湖鄉", city: "雲林縣", district: "口湖鄉" },
  { site_id: "雲林縣四湖鄉", city: "雲林縣", district: "四湖鄉" },
  { site_id: "雲林縣元長鄉", city: "雲林縣", district: "元長鄉" },
  { site_id: "嘉義縣番路鄉", city: "嘉義縣", district: "番路鄉" },
  { site_id: "嘉義縣梅山鄉", city: "嘉義縣", district: "梅山鄉" },
  { site_id: "嘉義縣竹崎鄉", city: "嘉義縣", district: "竹崎鄉" },
  { site_id: "嘉義縣阿里山鄉", city: "嘉義縣", district: "阿里山鄉" },
  { site_id: "嘉義縣中埔鄉", city: "嘉義縣", district: "中埔鄉" },
  { site_id: "嘉義縣大埔鄉", city: "嘉義縣", district: "大埔鄉" },
  { site_id: "嘉義縣水上鄉", city: "嘉義縣", district: "水上鄉" },
  { site_id: "嘉義縣鹿草鄉", city: "嘉義縣", district: "鹿草鄉" },
  { site_id: "嘉義縣太保市", city: "嘉義縣", district: "太保市" },
  { site_id: "嘉義縣朴子市", city: "嘉義縣", district: "朴子市" },
  { site_id: "嘉義縣東石鄉", city: "嘉義縣", district: "東石鄉" },
  { site_id: "嘉義縣六腳鄉", city: "嘉義縣", district: "六腳鄉" },
  { site_id: "嘉義縣新港鄉", city: "嘉義縣", district: "新港鄉" },
  { site_id: "嘉義縣民雄鄉", city: "嘉義縣", district: "民雄鄉" },
  { site_id: "嘉義縣大林鎮", city: "嘉義縣", district: "大林鎮" },
  { site_id: "嘉義縣溪口鄉", city: "嘉義縣", district: "溪口鄉" },
  { site_id: "嘉義縣義竹鄉", city: "嘉義縣", district: "義竹鄉" },
  { site_id: "嘉義縣布袋鎮", city: "嘉義縣", district: "布袋鎮" },
  { site_id: "屏東縣屏東市", city: "屏東縣", district: "屏東市" },
  { site_id: "屏東縣三地門鄉", city: "屏東縣", district: "三地門鄉" },
  { site_id: "屏東縣霧臺鄉", city: "屏東縣", district: "霧臺鄉" },
  { site_id: "屏東縣瑪家鄉", city: "屏東縣", district: "瑪家鄉" },
  { site_id: "屏東縣九如鄉", city: "屏東縣", district: "九如鄉" },
  { site_id: "屏東縣里港鄉", city: "屏東縣", district: "里港鄉" },
  { site_id: "屏東縣高樹鄉", city: "屏東縣", district: "高樹鄉" },
  { site_id: "屏東縣鹽埔鄉", city: "屏東縣", district: "鹽埔鄉" },
  { site_id: "屏東縣長治鄉", city: "屏東縣", district: "長治鄉" },
  { site_id: "屏東縣麟洛鄉", city: "屏東縣", district: "麟洛鄉" },
  { site_id: "屏東縣竹田鄉", city: "屏東縣", district: "竹田鄉" },
  { site_id: "屏東縣內埔鄉", city: "屏東縣", district: "內埔鄉" },
  { site_id: "屏東縣萬丹鄉", city: "屏東縣", district: "萬丹鄉" },
  { site_id: "屏東縣潮州鎮", city: "屏東縣", district: "潮州鎮" },
  { site_id: "屏東縣泰武鄉", city: "屏東縣", district: "泰武鄉" },
  { site_id: "屏東縣來義鄉", city: "屏東縣", district: "來義鄉" },
  { site_id: "屏東縣萬巒鄉", city: "屏東縣", district: "萬巒鄉" },
  { site_id: "屏東縣崁頂鄉", city: "屏東縣", district: "崁頂鄉" },
  { site_id: "屏東縣新埤鄉", city: "屏東縣", district: "新埤鄉" },
  { site_id: "屏東縣南州鄉", city: "屏東縣", district: "南州鄉" },
  { site_id: "屏東縣林邊鄉", city: "屏東縣", district: "林邊鄉" },
  { site_id: "屏東縣東港鎮", city: "屏東縣", district: "東港鎮" },
  { site_id: "屏東縣琉球鄉", city: "屏東縣", district: "琉球鄉" },
  { site_id: "屏東縣佳冬鄉", city: "屏東縣", district: "佳冬鄉" },
  { site_id: "屏東縣新園鄉", city: "屏東縣", district: "新園鄉" },
  { site_id: "屏東縣枋寮鄉", city: "屏東縣", district: "枋寮鄉" },
  { site_id: "屏東縣枋山鄉", city: "屏東縣", district: "枋山鄉" },
  { site_id: "屏東縣春日鄉", city: "屏東縣", district: "春日鄉" },
  { site_id: "屏東縣獅子鄉", city: "屏東縣", district: "獅子鄉" },
  { site_id: "屏東縣車城鄉", city: "屏東縣", district: "車城鄉" },
  { site_id: "屏東縣牡丹鄉", city: "屏東縣", district: "牡丹鄉" },
  { site_id: "屏東縣恆春鎮", city: "屏東縣", district: "恆春鎮" },
  { site_id: "屏東縣滿州鄉", city: "屏東縣", district: "滿州鄉" },
  { site_id: "宜蘭縣宜蘭市", city: "宜蘭縣", district: "宜蘭市" },
  { site_id: "宜蘭縣頭城鎮", city: "宜蘭縣", district: "頭城鎮" },
  { site_id: "宜蘭縣礁溪鄉", city: "宜蘭縣", district: "礁溪鄉" },
  { site_id: "宜蘭縣壯圍鄉", city: "宜蘭縣", district: "壯圍鄉" },
  { site_id: "宜蘭縣員山鄉", city: "宜蘭縣", district: "員山鄉" },
  { site_id: "宜蘭縣羅東鎮", city: "宜蘭縣", district: "羅東鎮" },
  { site_id: "宜蘭縣三星鄉", city: "宜蘭縣", district: "三星鄉" },
  { site_id: "宜蘭縣大同鄉", city: "宜蘭縣", district: "大同鄉" },
  { site_id: "宜蘭縣五結鄉", city: "宜蘭縣", district: "五結鄉" },
  { site_id: "宜蘭縣冬山鄉", city: "宜蘭縣", district: "冬山鄉" },
  { site_id: "宜蘭縣蘇澳鎮", city: "宜蘭縣", district: "蘇澳鎮" },
  { site_id: "宜蘭縣南澳鄉", city: "宜蘭縣", district: "南澳鄉" },
  { site_id: "宜蘭縣釣魚臺", city: "宜蘭縣", district: "釣魚臺" },
  { site_id: "花蓮縣花蓮市", city: "花蓮縣", district: "花蓮市" },
  { site_id: "花蓮縣新城鄉", city: "花蓮縣", district: "新城鄉" },
  { site_id: "花蓮縣秀林鄉", city: "花蓮縣", district: "秀林鄉" },
  { site_id: "花蓮縣吉安鄉", city: "花蓮縣", district: "吉安鄉" },
  { site_id: "花蓮縣壽豐鄉", city: "花蓮縣", district: "壽豐鄉" },
  { site_id: "花蓮縣鳳林鎮", city: "花蓮縣", district: "鳳林鎮" },
  { site_id: "花蓮縣光復鄉", city: "花蓮縣", district: "光復鄉" },
  { site_id: "花蓮縣豐濱鄉", city: "花蓮縣", district: "豐濱鄉" },
  { site_id: "花蓮縣瑞穗鄉", city: "花蓮縣", district: "瑞穗鄉" },
  { site_id: "花蓮縣萬榮鄉", city: "花蓮縣", district: "萬榮鄉" },
  { site_id: "花蓮縣玉里鎮", city: "花蓮縣", district: "玉里鎮" },
  { site_id: "花蓮縣卓溪鄉", city: "花蓮縣", district: "卓溪鄉" },
  { site_id: "花蓮縣富里鄉", city: "花蓮縣", district: "富里鄉" },
  { site_id: "臺東縣臺東市", city: "臺東縣", district: "臺東市" },
  { site_id: "臺東縣綠島鄉", city: "臺東縣", district: "綠島鄉" },
  { site_id: "臺東縣蘭嶼鄉", city: "臺東縣", district: "蘭嶼鄉" },
  { site_id: "臺東縣延平鄉", city: "臺東縣", district: "延平鄉" },
  { site_id: "臺東縣卑南鄉", city: "臺東縣", district: "卑南鄉" },
  { site_id: "臺東縣鹿野鄉", city: "臺東縣", district: "鹿野鄉" },
  { site_id: "臺東縣關山鎮", city: "臺東縣", district: "關山鎮" },
  { site_id: "臺東縣海端鄉", city: "臺東縣", district: "海端鄉" },
  { site_id: "臺東縣池上鄉", city: "臺東縣", district: "池上鄉" },
  { site_id: "臺東縣東河鄉", city: "臺東縣", district: "東河鄉" },
  { site_id: "臺東縣成功鎮", city: "臺東縣", district: "成功鎮" },
  { site_id: "臺東縣長濱鄉", city: "臺東縣", district: "長濱鄉" },
  { site_id: "臺東縣金峰鄉", city: "臺東縣", district: "金峰鄉" },
  { site_id: "臺東縣大武鄉", city: "臺東縣", district: "大武鄉" },
  { site_id: "臺東縣達仁鄉", city: "臺東縣", district: "達仁鄉" },
  { site_id: "澎湖縣馬公市", city: "澎湖縣", district: "馬公市" },
  { site_id: "澎湖縣西嶼鄉", city: "澎湖縣", district: "西嶼鄉" },
  { site_id: "澎湖縣望安鄉", city: "澎湖縣", district: "望安鄉" },
  { site_id: "澎湖縣七美鄉", city: "澎湖縣", district: "七美鄉" },
  { site_id: "澎湖縣白沙鄉", city: "澎湖縣", district: "白沙鄉" },
  { site_id: "澎湖縣湖西鄉", city: "澎湖縣", district: "湖西鄉" },
  { site_id: "金門縣金沙鎮", city: "金門縣", district: "金沙鎮" },
  { site_id: "金門縣金湖鎮", city: "金門縣", district: "金湖鎮" },
  { site_id: "金門縣金寧鄉", city: "金門縣", district: "金寧鄉" },
  { site_id: "金門縣金城鎮", city: "金門縣", district: "金城鎮" },
  { site_id: "金門縣烈嶼鄉", city: "金門縣", district: "烈嶼鄉" },
  { site_id: "金門縣烏坵鄉", city: "金門縣", district: "烏坵鄉" },
  { site_id: "連江縣南竿鄉", city: "連江縣", district: "南竿鄉" },
  { site_id: "連江縣北竿鄉", city: "連江縣", district: "北竿鄉" },
  { site_id: "連江縣莒光鄉", city: "連江縣", district: "莒光鄉" },
  { site_id: "連江縣東引鄉", city: "連江縣", district: "東引鄉" },
];
export const roomInfo_sample = [
  {
    title: "台北市信義區豪宅",
    type: "豪宅",
    rent: 20000,
    floor: "15樓",
    legal_use: "住宅",
    orientation: "南",
    environment: "繁華",
    ownership: true,
    area: 80,
    short_term_rent: false,
    deposit: 40000,
    parking: true,
    parking_description: "含車位",
    management_method: true,
    management_fee: 5000,
    equipment: "家具齊全",
    special_features: "景觀視野佳",
    map_url: "https://maps.example.com/taipei-xinyi",
    nearby_schools: "國泰中學",
    nearby_markets: "信義市場",
    nearby_parks: "信義公園",
    nearby_transportation: "捷運信義線",
    ev_service: "無",
    images: [
      {
        fieldname: "image1",
        originalname: "image1.jpg",
        encoding: "7bit",
        mimetype: "image/jpeg",
        buffer: Buffer.from([1, 2, 3, 4, 5]),
        size: 5120,
      },
      {
        fieldname: "image2",
        originalname: "image2.jpg",
        encoding: "7bit",
        mimetype: "image/jpeg",
        buffer: Buffer.from([6, 7, 8, 9, 10]),
        size: 5120,
      },
    ],
    contact_info: {
      phone: "0912345678",
      line_id: "taipei_xinyi",
    },
    description:
      "這間豪宅位於台北市信義區，擁有80平米的寬敞空間，南向戶型，位於15樓，擁有絕佳的景觀視野。房屋裝修精美，家具齊全，適合長期居住。鄰近捷運信義線，交通便利，附近有國泰中學和信義市場等生活設施。",
    city: "台北市",
    district: "信義區",
    street_number: "松仁路123號",
  },
  {
    title: "台中市西區美寓",
    type: "美寓",
    rent: 15000,
    floor: "5樓",
    legal_use: "住宅",
    orientation: "東",
    environment: "寧靜",
    ownership: true,
    area: 60,
    short_term_rent: true,
    deposit: 30000,
    parking: false,
    parking_description: "無車位",
    management_method: false,
    management_fee: null,
    equipment: "基本家具",
    special_features: "近市中心",
    map_url: "https://maps.example.com/taichung-west",
    nearby_schools: "西區國小",
    nearby_markets: "西區市場",
    nearby_parks: "西區公園",
    nearby_transportation: "公車站",
    ev_service: "無",
    images: [
      {
        fieldname: "image3",
        originalname: "image3.jpg",
        encoding: "7bit",
        mimetype: "image/jpeg",
        buffer: Buffer.from([11, 12, 13, 14, 15]),
        size: 4096,
      },
      {
        fieldname: "image4",
        originalname: "image4.jpg",
        encoding: "7bit",
        mimetype: "image/jpeg",
        buffer: Buffer.from([16, 17, 18, 19, 20]),
        size: 4096,
      },
    ],
    contact_info: {
      phone: "0987654321",
      line_id: "taichung_west",
    },
    description:
      "這是一間位於台中市西區的美寓，擁有60平米的居住空間，東向戶型，位於5樓，適合短期租賃。鄰近市中心，生活便利，附近有西區國小和市場，適合家庭或個人居住。",
    city: "台中市",
    district: "西區",
    street_number: "建國北路456號",
  },
];

export const user_sample = [
  {
    id: "66f5a16c8c5e7d8f89cfae21",
    email: "user1@example.com",
    phone: "0912000001",
    username: "user1",
    password: "password1",
    name: "User 1",
    token: "token1",
    isLandlord: true,
    isadmin: true,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c038",
        title: "台北市信義區豪宅",
      },
      {
        _id: "66bad047fbbd4e4ece02c03b",
        title: "台南市中西區商用大樓",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae22",
    email: "user2@example.com",
    phone: "0912000002",
    username: "user2",
    password: "password2",
    name: "User 2",
    token: "token2",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c03c",
        title: "桃園市桃園區住宅",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae23",
    email: "user3@example.com",
    phone: "0912000003",
    username: "user3",
    password: "password3",
    name: "User 3",
    token: "token3",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c03d",
        title: "新竹市東區公寓",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae24",
    email: "user4@example.com",
    phone: "0912000004",
    username: "user4",
    password: "password4",
    name: "User 4",
    token: "token4",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c039",
        title: "台中市西區美寓",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae25",
    email: "user5@example.com",
    phone: "0912000005",
    username: "user5",
    password: "password5",
    name: "User 5",
    token: "token5",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c03a",
        title: "高雄市三民區辦公室",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae26",
    email: "user6@example.com",
    phone: "0912000006",
    username: "user6",
    password: "password6",
    name: "User 6",
    token: "token6",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66dd58bc25d2c811f5b573ec",
        title: "台北市信義區豪宅",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae27",
    email: "user7@example.com",
    phone: "0912000007",
    username: "user7",
    password: "password7",
    name: "User 7",
    token: "token7",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c038",
        title: "台北市信義區豪宅",
      },
      {
        _id: "66bad047fbbd4e4ece02c03b",
        title: "台南市中西區商用大樓",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae28",
    email: "user8@example.com",
    phone: "0912000008",
    username: "user8",
    password: "password8",
    name: "User 8",
    token: "token8",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c03d",
        title: "新竹市東區公寓",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae29",
    email: "user9@example.com",
    phone: "0912000009",
    username: "user9",
    password: "password9",
    name: "User 9",
    token: "token9",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c03c",
        title: "桃園市桃園區住宅",
      },
    ],
  },
  {
    id: "66f5a16c8c5e7d8f89cfae2a",
    email: "user10@example.com",
    phone: "0912000010",
    username: "user10",
    password: "password10",
    name: "User 10",
    token: "token10",
    isLandlord: true,
    isadmin: false,
    properties: [
      {
        _id: "66bad047fbbd4e4ece02c039",
        title: "台中市西區美寓",
      },
    ],
  },
];
export const reservation_sample = [
  {
    _id: '675e82b991c5f80820f84997',
    client_id: '6749691938ece2722d942bcf',
    landlord_id: '67565c39e34b1070dceeb3f2',
    contactphone: '0912000002',
    email: 'user2@example.com',
    reservationtype: '預約回電',
    reservationtime: '2024-12-15T07:18:17.722Z',
    message: '我對這個物件有興趣，還請協助安排預約看屋時間'
  }
];
